### PR TITLE
add headers to get method

### PR DESCRIPTION
**Pull request by jochen-lienhard**
fist commit is to add headers to the get method
perhaps other commits will follow for curl-adapter and tests if need.

### CODE REVIEW

**Comment by jochen-lienhard** [comment]
Do you think we need a test for the headers?

**Comment by jochen-lienhard** [comment]
I'm not sure, if this is the right place for a curl adapter. 
Please let me know, if I shall remove it or if I shall add some test for this.

**Comment by jochen-lienhard** [comment]
Perhaps a better solution can be, building a HttpsService.php that always uses curl.

**Comment by demiankatz** [comment]
The header part looks good, but it would be nice to add a test for it so we maintain 100% test coverage. Modeling it on one of the existing get-related tests but setting up the adapter so that it expects setHeaders to be called with the headers passed to get should do the job.

Regarding curlify, I don't think we need it. There's already a setDefaultAdapter method, plus the adapter can be specified through the default options passed to the constructor of the service (and speaking of this: in VuFind itself, you can configure the CURL adapter as the default by using the [Http] adapter setting in config.ini to specify the name of the CURL adapter class).

Thanks for the progress on this!

**Comment by jochen-lienhard** [comment]
curlify is removed. Hmmm ... can I add to the config.ini this entry in the DAIAJSON pull request?
; Using a curl Adapter instead of the the defaultAdapter (Socket)
; adapter = 'Zend\Http\Client\Adapter\Curl' 

I have problem to understand how the get-releated tests work and be called. I just put a method, but I don't think, it will test the right thing. Doesn't we need a 'Zend/Http/Header' for checking if the header is set?

**Comment by demiankatz** [comment]
Yes, adding those comments to config.ini is a good idea.

The key part of the test you've added is this:

<pre>
$adapter->expects($this->once())
    ->method('write')
    ->with(
        $this->equalTo('GET'),
        $this->equalTo(
            new \Zend\Uri\Http('http://example.tld')
        )
    );
</pre>

Each parameter of with() sets up an expectation of the value that will be passed to the method. I believe that HTTP headers are sent to write() as the fourth parameter, so you probably just need to add two more $this->equalTo() checks to cover the third and fourth parameters.

Are you able to actually run the tests on your system? That would obviously make this a lot easier! If you're not set up to conveniently do that, let me know and I should be able to fill in the rest of the test pretty easily. If you need help with the setup, let me know. I think if you just install Phing and PHPUnit and then run "phing phpunitfast" inside the vufindhttp directory, it should work...

**Comment by jochen-lienhard** [comment]
I think it works now. What is your opinion?

**Comment by demiankatz** [comment]
Looks good. I've manually merged this to master and flagged a new release of the library. I'll update the dependencies of the VuFind master branch to include this shortly.

**Pull request closed without merging**
