### PR TITLE
Added a SOCKS 5 proxy compatibility

### PR DESCRIPTION
**Pull request by jirislav**
It should be enough to include the socks5 condition into VuFind\Service\Factory::getHttp(ServiceManager $sm) as it is here:
https://github.com/moravianlibrary/VuFind-2.x/blob/master/module/CPK/src/CPK/Service/Factory.php#L66-L67

Then, just set in config, [Proxy] section this variable:
socks5 = true

### CODE REVIEW

**Comment by demiankatz** [comment]
Thanks for sharing this! Just a couple of things:

1.) As you can see, Travis failed due to some minor style complaints. We should fix those before merging. I'm happy to do this for you if you don't have time.

2.) Rather than having a socks5 boolean setting, would it be better to have a proxy_type setting which could be set to socks5 or default? That will make it easier for us to implement additional proxy strategies in the future if we find that we need them.

Let me know what you think, and I'll try to get this merged as soon as we reach a consensus!

Thanks again!

**Comment by jirislav** [comment]
It is a pleasure sharing these little improvements!

I've fixed the travis warnings

Also your idea about setting 'proxy_type' sounds really good as it'll be ready for later upgrades. I'm going to update it now.

Thank you for such quick response too!

**Comment by jirislav** [comment]
Okay, now it should be easily configurable in [Proxy] section - it just needs to be implemented in the VuFind\Service\Factory::getHttp() method - I'm on it.

**Comment by demiankatz** [comment]
Thanks, looking good! I made a couple of minor tweaks and added a test case, and I've pushed that to master.

**Comment by demiankatz** [comment]
I'm making a 2.0.0 release of this library (since recent commits have raised the minimum PHP requirement) and will incorporate that into VuFind master shortly.

**Comment by jirislav** [comment]
Thank you too - for chance to contribute :)

**Pull request closed without merging**
