### PR TITLE
Additionnal test against $host

### PR DESCRIPTION
**Pull request by mathieugrimault**
isLocal('') returns false -> client is proxified

### CODE REVIEW

**Comment by mathieugrimault** [comment]
My covers setup is : calling first a local servlet (REST api OAuth 1.0 - provider Electre) then Google, Amazon, etc. So i need firstly a non proxified client then proxified clients.

Cant figure out/debug why i need this additionnal test but it's working... 

Config.ini : 
coverimages = Google,Amazon,LibraryThing:XXXX,OpenLibrary
[Http]
sslcapath = "/etc/ssl/certs" ; e.g. for Debian systems
sslverifypeer = false
sslverifypeername = false
;sslcafile = "/etc/pki/tls/cert.pem" ; e.g. for CentOS systems
; default timeout if not overridden by more specific code/settings
timeout = 5
; Using a curl Adapter instead of the the defaultAdapter (Socket)
adapter = "Zend\Http\Client\Adapter\Curl"

**Comment by demiankatz** [comment]
@mathieugrimault, did you close this PR because it is no longer necessary? Did you figure out what was going on, or did you close the PR by accident? Please let me know if you need me to investigate this further. Thanks!

**Comment by mathieugrimault** [comment]
Hi, this is driving me crazy. The solution i found was wrong... Sorry for that PR :(

I am still digging how to specify proxy at every client->send(...) or having multiples clients AND using curl adapter to ignore ssl checks.

**Comment by demiankatz** [comment]
@mathieugrimault, in theory, the [Proxy] section of config.ini ought to be affecting every $client->send as long as all clients are created through the central HTTP service (which they should be). In practice, it's hard to test this code without a real proxy setup, and the possible combinations of adapters and proxies could certainly cause problems that have not been detected.

Have you tried experimenting with different proxy type settings? (See [here](https://github.com/vufind-org/vufind/blob/master/config/vufind/config.ini#L1115)).

Let me know if I can be of any further assistance. Unfortunately, I don't have much expertise on dealing with proxies, but if you need help with general troubleshooting, let me know.

**Pull request closed without merging**
